name: webcrawler
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

#dependencies:
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0


dependencies:
  html: ^0.13.3+3
  http: ^0.12.0
  stream_channel: ^2.0.0
  synchronized: ^2.1.1